# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test-ci:lib
      - run: npm run build-ci:lib
      - run: cp README.md dist/@ngxp/store-service/README.md
      
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - run: pwd
      - run: ls -l dist/@ngxp/store-service
    
      
    
      
